---

- name: "Build the /etc/hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ip'] }} {{item}}"
    state: present
  when: hostvars[item]['ip'] is defined
  with_items: '{{ groups.all }}'
